name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: deps
      run: |
        sudo add-apt-repository ppa:deadsnakes/ppa
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends python3.8 python3.8-distutils build-essential libevent-dev libjpeg-turbo8-dev uuid-dev libbsd-dev
        sudo python3.8 get-pip.py
        sudo python3.8 -m pip install tox
    - name: make
      run: make
    - name: make tox
      run: make tox
