name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt deps
      run: sudo apt-get install python3 python3-pip build-essential libevent-dev libjpeg-turbo8-dev uuid-dev libbsd-dev
    - name: pip deps
      run: sudo pip install tox
    - name: make
      run: make
    - name: make tox
      run: make tox
